#!/usr/bin/env python
"""Generate a printable PDF session report via matplotlib's PdfPages (no extra
deps). 3 pages: Overview (KPIs + shot chart + coach review), Trends (fatigue
chart + consistency + what-fades), Insights (make/feel drivers + zones + best).

Usage:  python tools/export_pdf.py data/out/session_0629_full
API:    build_session_pdf(session_dir) -> bytes
"""

from __future__ import annotations

import io
import os
import sys
import textwrap

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _wrap(text, width):
    out = []
    for ln in text.splitlines():
        out.extend(textwrap.wrap(ln, width) or [""])
    return "\n".join(out)


def _clean_md(s):
    s = (s.replace("**", "").replace("###", "").replace("- ", "• ")
         .replace("_", ""))
    # drop emoji / symbols the PDF core font can't render (keep — • ° → etc.)
    return "".join(ch for ch in s if ord(ch) < 0x2600)


def _table(fig, dframe, rect, title):
    ax = fig.add_axes(rect)
    ax.axis("off")
    ax.set_title(title, fontsize=11, loc="left", weight="bold", pad=6)
    if dframe.empty:
        ax.text(0, 0.5, "(no data)", fontsize=9, color="#888")
        return
    t = ax.table(cellText=dframe.round(2).astype(object).values,
                 colLabels=list(dframe.columns), loc="center", cellLoc="center")
    t.auto_set_font_size(False)
    t.set_fontsize(7.5)
    t.scale(1, 1.35)


def _footer(fig):
    fig.text(0.06, 0.02,
             "Angles are foreshortened by the single camera (consistent within a "
             "zone; absolute values approximate until calibration). Make% and "
             "real-feet are low-confidence. Generated by ShotLab.",
             fontsize=6.5, color="#999", wrap=True)


def _kpi_line(df, volume_stats):
    parts = []
    if "made" in df.columns:
        m = df[df["made"].isin([True, False, "True", "False"])]
        if len(m):
            parts.append(f"Make {100*m['made'].isin([True,'True']).mean():.0f}%")
    for c, lbl, u in [("apex_above_rim_ft", "arc/rim", " ft"),
                      ("release_height_ft", "release", " ft"),
                      ("jump_height_ft", "jump", " ft"),
                      ("tempo_dip_to_release_s", "tempo", " s")]:
        if c in df.columns and df[c].notna().sum() >= 3:
            parts.append(f"{lbl} {df[c].mean():.2f}{u}")
    vs = volume_stats(df)
    parts.append(f"streak {vs['longest_make_streak']}")
    return "   ·   ".join(parts)


def build_session_pdf(session_dir: str) -> bytes:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.image as mpimg
    from matplotlib.backends.backend_pdf import PdfPages

    from shotlab.viz import draw_court, _norm_made
    from shotlab.session import consistency_stats, fatigue_breakdown, volume_stats
    from shotlab.correlate import (correlate_makes, summarize_make_drivers,
                                   correlate_feel, summarize_feel_drivers)

    df = pd.read_csv(os.path.join(session_dir, "session_shots.csv"))
    name = os.path.basename(session_dir.rstrip("/\\"))
    n = len(df)
    dur = df["elapsed_min"].max() if "elapsed_min" in df else 0

    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        # ---- Page 1: overview ----
        fig = plt.figure(figsize=(8.5, 11))
        fig.text(0.06, 0.955, f"ShotLab — {name}", fontsize=19, weight="bold")
        fig.text(0.06, 0.93, f"{n} shots  ·  {dur:.0f} min session", fontsize=11,
                 color="#555")
        fig.text(0.06, 0.905, _kpi_line(df, volume_stats), fontsize=10.5,
                 color="#111")
        ax = fig.add_axes([0.06, 0.44, 0.44, 0.42])
        draw_court(ax, df)
        ax.set_title("Shot chart (make% by zone)", fontsize=11, weight="bold")
        rp = os.path.join(session_dir, "review.md")
        review = open(rp, encoding="utf-8").read() if os.path.exists(rp) else ""
        fig.text(0.54, 0.86, "Coach review", fontsize=11, weight="bold")
        fig.text(0.54, 0.845, _wrap(_clean_md(review), 52), fontsize=8, va="top")
        _footer(fig)
        pdf.savefig(fig); plt.close(fig)

        # ---- Page 2: trends & consistency ----
        fig = plt.figure(figsize=(8.5, 11))
        fig.text(0.06, 0.955, "Trends & consistency", fontsize=16, weight="bold")
        png = os.path.join(session_dir, "session_chart.png")
        if os.path.exists(png):
            ax = fig.add_axes([0.06, 0.55, 0.88, 0.36])
            ax.imshow(mpimg.imread(png)); ax.axis("off")
        cons = consistency_stats(df)
        _table(fig, cons, [0.06, 0.30, 0.88, 0.18],
               "Consistency (within-zone spread — lower = more repeatable)")
        fb = fatigue_breakdown(df)
        if not fb.empty:
            fb = fb[["metric", "first_half", "second_half", "change_in_sd"]]
        _table(fig, fb, [0.06, 0.08, 0.88, 0.16], "What fades as you tire")
        _footer(fig)
        pdf.savefig(fig); plt.close(fig)

        # ---- Page 3: insights ----
        fig = plt.figure(figsize=(8.5, 11))
        fig.text(0.06, 0.955, "Insights", fontsize=16, weight="bold")
        rows = df.to_dict("records")
        for r in rows:
            r["made"] = _norm_made(r.get("made"))
        make_txt = _clean_md(summarize_make_drivers(correlate_makes(rows)))
        fig.text(0.06, 0.92, "What tracks with your makes", fontsize=11, weight="bold")
        fig.text(0.06, 0.905, _wrap(make_txt, 95), fontsize=8, va="top")
        feel_txt = _clean_md(summarize_feel_drivers(correlate_feel(rows)))
        fig.text(0.06, 0.66, "What tracks with your feel", fontsize=11, weight="bold")
        fig.text(0.06, 0.645, _wrap(feel_txt, 95), fontsize=8, va="top")
        if "zone" in df.columns:
            agg = (df.groupby("zone")
                   .agg(shots=("zone", "count"),
                        avg_entry=("entry_angle_deg", "mean")
                        if "entry_angle_deg" in df.columns else ("zone", "count"))
                   .round(1).reset_index())
            _table(fig, agg, [0.06, 0.30, 0.55, 0.2], "By zone")
        _footer(fig)
        pdf.savefig(fig); plt.close(fig)

    return buf.getvalue()


def main(argv=None):
    args = argv or sys.argv[1:]
    d = args[0] if args else "data/out/session_0629_full"
    if not os.path.exists(os.path.join(d, "session_shots.csv")):
        print(f"no session_shots.csv in {d}")
        return 1
    out = os.path.join(d, "report.pdf")
    with open(out, "wb") as f:
        f.write(build_session_pdf(d))
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
